package com.ingramcontent.dataverse.utility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constant implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Constant() {
    }

    public static String PRODUCT_ALL_TIMS_POLAR = "product_all_tims_polar";
    public static String ITEM_LOAD = "ItemLoad";
    public static String PUBLISHER_LOAD = "PublisherLoad";
    public static String PROD = "PROD";
    public static String XFRM = "XFRM";
    public static String CNSM = "CNSM";
    public static int ZERO = 0;
     public static boolean TRUE_VAL = true;

}