package com.ingramcontent.dataverse.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PipelineThreshold implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int publisherLoad;
	private int itemLoad;

	private int productAllTimsPolar;

	public PipelineThreshold() {
	}

	public int getPublisherLoad() {
		return this.publisherLoad;
	}

	public void setPublisherLoad(int publisherLoad) {
		this.publisherLoad = publisherLoad;
	}

	public int getItemLoad() {
		return this.itemLoad;
	}

	public void setItemLoad(int itemLoad) {
		this.itemLoad = itemLoad;
	}

	public int getProductAllTimsPolar() {
		return this.productAllTimsPolar;
	}

	public void setProductAllTimsPolar(int productAllTimsPolar) {
		this.productAllTimsPolar = productAllTimsPolar;
	}

	public PipelineThreshold(int publisherLoad, int itemLoad,
			int productAllTimsPolar) {
		this.publisherLoad = publisherLoad;
		this.itemLoad = itemLoad;
		this.productAllTimsPolar = productAllTimsPolar;
	}

}